Added lab2
kpi-keoa/kpi-computer-architecture-course pull request #14
Opened 2019-09-15 13:29 UTC by M0rel

1) Created register file
2) Created tests
[waveform.zip](https://github.com/kpi-keoa/kpi-computer-architecture-course/files/3613790/waveform.zip)

2019-09-15 22:27 UTC, thodnev requested changes
Что исправить:
- дополнить отчет (выводы тоже)
- переименовать `registerFile_inst.v`, что бы было понятно, что это тест
- остальное указал в комментариях

2019-09-15 22:27 UTC, thodnev commented on dk72_kharchuk/lab2_register_file/README.rst
> +Створення файлу регістрового файла ядра MIPS
тавтологией не страдают тавтологией

2019-09-15 22:27 UTC, thodnev commented on dk72_kharchuk/lab2_register_file/src/registerFile_inst.v
> +registerFile registerFile_inst
Об этом писал [тут](https://github.com/kpi-keoa/kpi-computer-architecture-course/pull/11#discussion_r324482447)

2019-09-15 22:27 UTC, thodnev commented on dk72_kharchuk/lab2_register_file/src/registerFile_inst.v
> +/*	for (int i = 0; i < 32; i++) begin
Закомментированные intermediate-фрагменты кода (не объясняют чего-то и так далее) не должны присутствовать в исходнике

2019-09-15 22:27 UTC, thodnev commented on dk72_kharchuk/lab2_register_file/src/registerFile_inst.v
> +
Лишние пустые строки в конце файла

2019-09-15 22:27 UTC, thodnev commented on dk72_kharchuk/lab2_register_file/README.rst
> +.. image:: media/waveform.png
Слишком много неинформативного пространства. Скриншот необходимо обрезать

2019-09-15 22:28 UTC, thodnev commented
Достойная работа. Тянет на максимум. Исправьте [ошибки](https://github.com/kpi-keoa/kpi-computer-architecture-course/pull/14#pullrequestreview-288384403)

2019-09-16 08:43 UTC, M0rel commented on dk72_kharchuk/lab2_register_file/README.rst
> +Створення файлу регістрового файла ядра MIPS
виправлено

2019-09-16 08:45 UTC, vadym-kharchuk commented on dk72_kharchuk/lab2_register_file/src/registerFile_inst.v
> +registerFile registerFile_inst
Не дуже зрозумів що тут треба було зробити. Виправив так як розібрався

2019-09-16 08:46 UTC, M0rel commented on dk72_kharchuk/lab2_register_file/src/registerFile_inst.v
> +/*	for (int i = 0; i < 32; i++) begin
виправлено

2019-09-16 08:46 UTC, M0rel commented on dk72_kharchuk/lab2_register_file/src/registerFile_inst.v
> +
виправлено

2019-09-16 08:46 UTC, M0rel commented on dk72_kharchuk/lab2_register_file/README.rst
> +.. image:: media/waveform.png
виправлено

2019-09-16 17:14 UTC, thodnev approved these changes

2019-09-16 17:15 UTC, thodnev commented
Отлично! Оценка за выполнение: 5 баллов (максимум)

Обратите внимание, решенные проблемы лучше отмечать как Resolved вместо комментариев

2019-09-16 17:15 UTC, merged