lab2 first commit
kpi-keoa/kpi-computer-architecture-course pull request #17
Opened 2019-09-16 15:14 UTC by sashalavrus

Выполнил вторую лабу.  Реализовал "регистровый файл", провел симуляцию в Cadence incisive.
Хорошего вечера

[waveform.zip](https://github.com/kpi-keoa/kpi-computer-architecture-course/files/3616904/waveform.zip)

2019-09-16 20:08 UTC, thodnev requested changes
Замечания:
- у вас в коммиты по второй работе попали файлы из первой. Исправьте
- `waveform.PNG` должен быть `.png`
- часть замечаний из [первой](https://github.com/kpi-keoa/kpi-computer-architecture-course/pull/16#pullrequestreview-288787845) лабораторной актуальна и здесь 
- `lab2.v.bak` и друзья – лишние временные файлы. Добавьте в `.gitignore`
- Теста так и не увидел. Это должен быть либо скрипт, задающий сигналы в симуляторе. Либо аналогичный файл на одном из HDL
- отчет необходимо дописать (в.т.ч. выводы)
- остальное в комментариях

2019-09-16 20:08 UTC, thodnev commented on dk71_lavrusenko/lab2_register_file/.gitignore
> +*.txt
Вот тут перевода строки не хватает

2019-09-16 20:08 UTC, thodnev commented on dk71_lavrusenko/lab2_register_file/README.rst
> +.. image:: media/waveform.PNG
Обрежьте изображение

2019-09-16 20:11 UTC, thodnev commented
Работа хорошая (не считая слегка извращенного мультиплексора и малого объема отчета).
Исправьте замечания [тут](https://github.com/kpi-keoa/kpi-computer-architecture-course/pull/17#pullrequestreview-288866720). После исправления возможен максимальный балл.

2019-09-17 13:56 UTC, sashalavrus commented
Сохранил сигналы:

[waveform_file.zip](https://github.com/kpi-keoa/kpi-computer-architecture-course/files/3621677/waveform_file.zip)

2019-09-17 14:42 UTC, thodnev commented
[Вот](https://github.com/kpi-keoa/kpi-computer-architecture-course/tree/23639906449426cda5ac5240a0070977d3f72fad/dk71_lavrusenko) предлагаемое в PR в итоге.
PR нарушает целостность репозитория. В текущем виде принять не представляется возможным. Исправьте до защиты.

- Отчет все так же [рендерится плохо](https://github.com/kpi-keoa/kpi-computer-architecture-course/blob/23639906449426cda5ac5240a0070977d3f72fad/dk71_lavrusenko/lab2_register_file/README.rst)
- Отчет не был должным образом дополнен
- Имена файлов не исправлены
- Тест (в виде скрипта или HDL) как отсутствовал, так и отсутствует

Оценка за выполнение: 2.5/5

2019-09-23 12:11 UTC, closed without merging