lab 4
kpi-keoa/kpi-computer-architecture-course pull request #41
Opened 2019-09-30 18:37 UTC by M0rel

1) Created ALU
2) Created tests
3) Created report
[waveform.zip](https://github.com/kpi-keoa/kpi-computer-architecture-course/files/3672730/waveform.zip)

2019-09-30 21:03 UTC, thodnev requested changes
Замечания:
- `add_sub_inst.v` этот файл не нужен. У вас весь тест в TB верхнего уровня иерархии
- остальное в комментариях

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/add_sub.v
> +module add_sub#(parameter WIDTH = 32) (
пробела не хватает перед `#`

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/barrel_shifter.v
> +		`SRA:  result = data_mod2[63:32];
тут должен быть `default`

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/barrel_shifter.v
> +module barrel_shifter #(parameter WIDTH = 32)(
отсутствует пробел между `)(`

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/logic_op.v
> +module logic_op #(parameter WIDTH = 32)(
отсутствует пробел между `)(`

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/mul_div.v
> +module mul_div #(parameter WIDTH = 32)(
отсутствует пробел `)(`

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/mul_div.v
> +assign mulO = in_A * in_B;
беззнаковый. Должен быть знаковым

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/mul_div.v
> +assign out = (in_opt[1]) ? result[WIDTH*2-1:WIDTH] : result[WIDTH-1:0];
ну и вот эта штука синтезируется в приоритетный мультиплексор, что добавит задержку.
Опишите с помощью `casez` и будет огонь

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/lab4_alu.v
> +mul_div #(WIDTH) md(.in_A(in_a), .in_B(in_b), .in_opt(in_opt[0]), .out(mulout));
слишком длинные строки, должны быть максимум 99 символов

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/lab4_alu.v
> +			default: alu_result = 0;
весь смысл `casez` и его `default` в don't care. В данном случае, это полный case. Но все равно, берите за привычку делать полные `casez` с
```SystemVerilog
default: alu_result = {WIDTH{1'bz}};
```

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/src/lab4_alu.v
> +		out_zero = ~|alu_result;
без подсветки синтаксиса `|` легко спутать с `l` или `I`. Поэтому, используйте скобки или пробелы: `~| alu_result`

2019-09-30 21:03 UTC, thodnev commented on dk72_kharchuk/lab4_alu/README.rst
> +.. image:: media/alu.png
не видно внутреннюю структуру модулей. Вся соль именно в ней, а не в том, как они подключены

2019-09-30 21:04 UTC, thodnev commented
Хорошая работа. Возможен максимум после исправления [этих](https://github.com/kpi-keoa/kpi-computer-architecture-course/pull/41#pullrequestreview-295244491) ошибок

2019-10-01 12:03 UTC, M0rel commented
Помилки виправленно, додаю нову вейформу 
[waveform.zip](https://github.com/kpi-keoa/kpi-computer-architecture-course/files/3676072/waveform.zip)

2019-10-02 06:54 UTC, merged