lab2_sarazhynskyi
kpi-keoa/kpi-computer-architecture-course pull request #51
Opened 2019-10-05 23:30 UTC by valentin5135

Здається повидаляв коміти. 

[Waveforms.tar.gz](https://github.com/kpi-keoa/kpi-computer-architecture-course/files/3693783/Waveforms.tar.gz)

2019-10-07 23:48 UTC, thodnev requested changes
Замечания:
- Исправьте лицензию. У вас все права принадлежать @NazarVolynko 
  ![это зашквар](https://user-images.githubusercontent.com/16870636/66356797-14262380-e975-11e9-820d-07d5ed94254f.png)
- В PR вошли файлы первой лабораторной. Это недопустимо. Под каждую работу отдельный PR
- Выводы необходимо дополнить. Формат должен хоть отдаленно соответствовать требованиям ДСТУ 3008:2015
- `lab2_register_file/media/lab2_scheme.bmp` — изображения в BMP, а также TIFF и других тяжеловесных форматах в репозиторий не принимаются
- остальное в комментариях

2019-10-07 23:48 UTC, thodnev commented on dk72_sarazhynskyi/lab2_register_file/src/lab2_tb.v
> +// applicable agreement for further details.
TB пишете вы, незачем подвязывать сюда лицензию Altera

2019-10-07 23:49 UTC, thodnev commented
Отличная работа, жаль, что так поздно. Исправьте замечания ([тут](https://github.com/kpi-keoa/kpi-computer-architecture-course/pull/51#pullrequestreview-298470777))
Особенно с файлами из первой лабораторной в коммите и лицензию

2019-10-08 19:43 UTC, valentin5135 commented
Повиправляв помилки, але не розумію як виправити LICENSE, так як він закомічений з іншої гілки, PR якої вже закритий, тому додав виправлений LICENSE до цієї гілки

2019-10-09 06:59 UTC, merged

2019-10-09 06:59 UTC, thodnev commented
Оценка за выполнение: 0/5